import "./globals.css";
import StoreManager from "@/components/storeManager/StoreManager";
import { CookiesProvider } from "next-client-cookies/server";
import { Toaster } from "@common-templates/shared/components/ui/toaster";

export const metadata = {
  title: "Client App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
      <CookiesProvider>
        {children}
        <Toaster />
        <StoreManager />
      </CookiesProvider>
      </body>
    </html>
  );
}
